### PR TITLE
fix: inspection was renamed to endpoints in code

### PR DESCRIPTION
**Pull request by Eagleman7**
Hello!

While setting up the inspection VPC from the example in the README i figured out that inspection was renamed to endpoints. This PR updates the documentation.

### CODE REVIEW

**Comment by Eagleman7** [comment]
Hey @drewmullen,

Did you have time to look at my PR's :) ?

**Comment by drewmullen** [comment]
The brain-iac on this module is @pablo19sc , I believe we permissions should be resolved now and can properly review

Ik there was a WIP feature, do you think we can review these first, Pablo?

Thanks for your patience, Dec is always busy internally but I also forgot to come back to these in the new year, eagleman

**Comment by pablo19sc** [comment]
Hello! I will check this during the week (quite busy weeks after Christmas). Sorry for the delay, and thank you for the PR!

**Review by pablo19sc — APPROVED** [review]
Approved. Sorry for the delay, and thank you for your PR! I promise to be faster in next ones :)

**Pull request merged**
